### ISSUE TITLE
Java/Spring Client can't access cluster

### ISSUE THREAD

**Issue by liwang-pivotal** [upmc-enterprises/elasticsearch-operator#107]
With Search Guard SSL is enabled, Java Client is not able to access cluster even provided node-keystore.jks, truststore.jks. 

The Client code snippet is as below:

```
Settings settings = Settings.settingsBuilder()
        .put("path.home", ".")
        .put("cluster.name", "myclustername")
        .put("searchguard.ssl.transport.enabled", true)
        .put("searchguard.ssl.transport.keystore_filepath", "node-keystore.jks")
        .put("searchguard.ssl.transport.truststore_filepath", "truststore.jks")
        .put("searchguard.ssl.transport.enforce_hostname_verification", false)              
        .build();

TransportClient client = TransportClient.builder()
        .settings(settings)
        .addPlugin(SearchGuardSSLPlugin.class)
        .build()
        .addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress(nodeHost, nodePort)));
```

Is this the proper settings to use? Any suggestions?

**Comment by stevesloka** [comment]
Hey @liwang-pivotal, what's the exception you're getting?

**Comment by liwang-pivotal** [comment]
@stevesloka The error is like
```
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{i7MyEKcHTYa0HmUET47YuA}{tcp.numerounocloud.com}{35.185.69.35:60012}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[elasticsearch-5.6.3.jar:5.6.3]
	at io.spring.esdemo.EsDemoApplication.run(EsDemoApplication.java:25) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	... 6 common frames omitted
```
However I checked the port is open and should be able to connect.
Anything wrong with my code snippet above? Is this the correct way to connect to k8s cluster created by this operator?
Thanks.

**Comment by liwang-pivotal** [comment]
@stevesloka Seems it's a Spring Data ElasticSearch issue. Once I replace it with ES Java client dependencies, it works for me.
