### ISSUE TITLE
minikube locking broken

### ISSUE THREAD

**Issue by kfox1111** [upmc-enterprises/elasticsearch-operator#116]
I'm trying to launch a cluster using the minikube example. its failing to launch with all elasticsearch containers displaying an error such as:

[2017-10-31T00:20:56,453][INFO ][o.e.n.Node               ] [4b9e027d-3216-4da9-b55d-846dfb048582] initializing ...
[2017-10-31T00:20:56,485][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [4b9e027d-3216-4da9-b55d-846dfb048582] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/data/data/myesdb]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/data/data/myesdb]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?

**Comment by kfox1111** [comment]
I tried to add '--loggger.env=TRACE' to the java opts, but the jvm complains. is there a way to add flags to elasticsearch?

**Comment by stevesloka** [comment]
How much memory does your minikube vm have? I've seen goofy things with elastic when I run without enough resources.

**Comment by kfox1111** [comment]
I launched it with 8 gigs. Its really not liking to take a lock.... I straced it and I do see the fcntl F_SETLK succeed though, which is puzzling.

**Comment by kfox1111** [comment]
I bumped the tag on the elasticsearch image to 5.6.3_0 as I see there is an image for that now. It did get past the locking issue, so I think that it was maybe a docker version that was incompatible with the older elasticsearch/lucene?

I hit another issue too. the init container trick to force in the sysctl setting is no longer applied in 1.8 as I think it graduated and they dropped the annotation support. I had to manually tweak the setting in 'minikube ssh'

The 5.6.3_0 image stays up and running but searchguard wont let the system work. So I think there may be an issue of compatibility between the released 0.0.9 operator and that container?

**Comment by stevesloka** [comment]
I was just testing the new 5.6.3 image. Let me finish that and see what's up. We did a switch on the SearchGuard plugin from SearchGuardTLS to just the plain searchguard as we're doing some thing with auth now.

**Comment by kfox1111** [comment]
ok, cool. please let me know if there is anything I can do to help debug. :)

**Comment by stevesloka** [comment]
Just for reference, what version of k8s are you using?

**Comment by kfox1111** [comment]
minikube version: v0.23.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by stevesloka** [comment]
I think the newer elastic images should work. I'm working through that right now since like you found the search guard stuff is broken. Will update very soon!

**Comment by stevesloka** [comment]
I've got a big PR to fix much of these issues, however, minikube is still broken for me. I was wondering if you could try out yours for me. 

Here are the two images that are updated:

- upmcenterprises/elasticsearch-operator:0.0.10-beta
- upmcenterprises/docker-elasticsearch-kubernetes:5.6.4_1

Here's the error I get on minikube, but not any other cluster:

```[2017-12-10T01:27:52,788][ERROR][c.f.s.s.t.SearchGuardSSLNettyTransport] [c29e49fe-2a22-4f43-9fb2-e1501c6384c3] SSL Problem Received fatal alert: certificate_unknown
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_131]
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:255) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1162) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1084) ~[netty-handler-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by stevesloka** [comment]
I just tested minikube using virtualbox and not xhyve, and it all worked. I can't tell why, but something with xhyve is broken.

**Comment by kfox1111** [comment]
I tried it again in minikube with kvm and got the same issue:
[2018-01-03T18:36:51,030][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [21ce0876-52fd-41ef-bcef-8ece9d07fa03] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/data/data/myesdb]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?

I used helm charts in the v0.0.10 release tarball.

**Comment by kfox1111** [comment]
I noticed the chart is using the older version of the container. bumping up to the newer version to see if that will fix things.

**Comment by kfox1111** [comment]
the newest tag does fix the issue and I have the whole stack successfully running in minikube. So I think the only thing left for this issue is a PR to update the default tag in the elasticsearch helm chart?

**Comment by kfox1111** [comment]
FYI, to get it to work I did have to:
minikube ssh
sudo sysctl -w vm.max_map_count=262144
# as well. and launched it like:
helm install elasticsearch -n foo --set 'image.tag=5.6.4_1,javaOpts="-Xms256m -Xmx256m"'

**Comment by stevesloka** [comment]
I think this should be resolved now, please re-open if not.
