### ISSUE TITLE
Getting an error on cluster initialization

### ISSUE THREAD

**Issue by erez-rabih** [upmc-enterprises/elasticsearch-operator#14]
Hi,

I just followed the tutorial and I'm getting an error on each of the ES nodes:
```
[2017-02-19T12:03:46,089][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] sslTransport protocols [TLSv1.2, TLSv1.1]
[2017-02-19T12:03:46,090][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] sslHTTP protocols [TLSv1.2, TLSv1.1]
[2017-02-19T12:03:47,845][INFO ][o.e.n.Node               ] initialized
[2017-02-19T12:03:47,846][INFO ][o.e.n.Node               ] [7s75x0J] starting ...
[2017-02-19T12:03:48,002][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.1.jar:5.1.1]
Caused by: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:187) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:246) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:220) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:130) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:585) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:182) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:188) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.start(Node.java:577) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:234) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:308) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
	... 6 more
[2017-02-19T12:03:48,893][INFO ][o.e.n.Node               ] [7s75x0J] stopping ...
[2017-02-19T12:03:48,897][INFO ][o.e.n.Node               ] [7s75x0J] stopped
[2017-02-19T12:03:48,898][INFO ][o.e.n.Node               ] [7s75x0J] closing ...
[2017-02-19T12:03:48,913][INFO ][o.e.n.Node               ] [7s75x0J] closed
```

Using K8s 1.5.2 on AWS.

**Comment by stevesloka** [comment]
There was another issue which ran into the problem, I'll have to update the base deployment or add a flag to do so. See: https://github.com/pires/docker-elasticsearch-kubernetes/issues/5#issuecomment-202655590

**Comment by stevesloka** [comment]
To get this working quickly, try setting an ENV variable `${NETWORK_HOST}` which will let you override that piece easily now.

**Comment by stevesloka** [comment]
hey @erez-rabih just wanted to check in and see if that worked for you?

**Comment by erez-rabih** [comment]
I ended up switching to https://github.com/pires/kubernetes-elasticsearch-cluster since the image is his and he had a workaround documented.

**Comment by stevesloka** [comment]
Ok sounds good, thanks!
