### ISSUE TITLE
"Could not get version from api server"

### ISSUE THREAD

**Issue by DimaBogdan-phie** [upmc-enterprises/elasticsearch-operator#151]
Hello!

Could you tell me please, what am I doing wrong? 

I have 2 node cluster on CentOS 7 where **kubernetes** has been deployed via **kubespray**.

```bash
[root@node1 ~]# kubectl --version
Kubernetes v1.8.3+coreos.0
[root@node2 ~]# kubelet --version
Kubernetes v1.9.3
```

When I try to deploy operator, I get:
```bash
[root@node1 ~]# kubectl create -f https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/example/controller.yaml -n operator
serviceaccount "elasticsearch-operator" created
clusterrole "elasticsearch-operator" created
clusterrolebinding "elasticsearch-operator" created
deployment "elasticsearch-operator" created
[root@node1 ~]# kubectl get po -n operator
NAME                                      READY     STATUS    RESTARTS   AGE
elasticsearch-operator-6f6f9c455f-lnffz   0/1       Running   2          1m
[root@node1 ~]# kubectl logs -f elasticsearch-operator-6f6f9c455f-lnffz -n operator
time="2018-02-18T18:57:12Z" level=info msg="elasticsearch operator starting up!"
time="2018-02-18T18:57:12Z" level=info msg="Using Variables:"
time="2018-02-18T18:57:12Z" level=info msg="   baseImage: upmcenterprises/docker-elasticsearch-kubernetes:5.3.1"
time="2018-02-18T18:57:12Z" level=info msg="Using InCluster k8s config"
time="2018-02-18T18:57:42Z" level=error msg="Could not get version from api server:Get https://10.233.0.1:443/version: dial tcp 10.233.0.1:443: i/o timeout"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xeb934b]

goroutine 1 [running]:
github.com/upmc-enterprises/elasticsearch-operator/pkg/k8sutil.newKubeClient(0x0, 0x0, 0xc4203aab40, 0xc4203bbd08, 0x6c0207, 0xc42007
c268, 0x0, 0x0, 0xc4203bbd50, 0x6c05de, ...)
        /Users/stevesloka/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/k8sutil/k8sutil.go:149 +0x1ab
github.com/upmc-enterprises/elasticsearch-operator/pkg/k8sutil.New(0x0, 0x0, 0x10f5dcb, 0x15, 0x1, 0x4dbea3, 0xc4202d9030)
        /Users/stevesloka/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/k8sutil/k8sutil.go:88 +0x4d
main.Main(0xecb393)
        /Users/stevesloka/godev/src/github.com/upmc-enterprises/elasticsearch-operator/cmd/operator/main.go:78 +0x1ad
main.main()
        /Users/stevesloka/godev/src/github.com/upmc-enterprises/elasticsearch-operator/cmd/operator/main.go:144 +0x22
```

![image](https://user-images.githubusercontent.com/33295616/36355780-87ad1c5c-14f9-11e8-9009-9906661be3c5.png)
![image](https://user-images.githubusercontent.com/33295616/36355845-a4e1b43a-14fa-11e8-946e-8012c74ac902.png)

**Comment by stevesloka** [comment]
One thing is weird that your nodes have different versions. Also, looks like node02 cannot talk to API server, is that the node the operator deployed to?

**Comment by DimaBogdan-phie** [comment]
Thank you! 
It was actually a version issue.
