### ISSUE TITLE
Cerebro error: [ConnectException: General SSLEngine problem]

### ISSUE THREAD

**Issue by Sneko** [upmc-enterprises/elasticsearch-operator#194]
Hi!

I just made the setup of a ElasticSearchCluster but when I'm trying to access Cerebro, it asks me to provide the host address. When I try the both following solutions I get an error:
- Select "es servers" host
- Input "https://elasticsearch-elasticsearch-cluster:9200"

 `[[37minfo[0m] play.api.Play - Application started (Prod)
[[37minfo[0m] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[[31merror[0m] application - 

! @77njpf95j - Internal server error, for (POST) [/cluster_changes] ->
 
play.api.UnexpectedException: Unexpected exception[ConnectException: General SSLEngine problem]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: java.net.ConnectException: General SSLEngine problem
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:160)
	at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:131)
	at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
Caused by: play.api.libs.ws.ssl.CompositeCertificateException: No trust manager was able to validate this certificate chain: # of exceptions = 2
	at play.api.libs.ws.ssl.CompositeX509TrustManager.checkServerTrusted(CompositeX509TrustManager.scala:88)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:999)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
[[31merror[0m] application - 

! @77njpf96j - Internal server error, for (POST) [/navbar] ->
 
play.api.UnexpectedException: Unexpected exception[ConnectException: General SSLEngine problem]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: java.net.ConnectException: General SSLEngine problem
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:160)
	at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:131)
	at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
Caused by: play.api.libs.ws.ssl.CompositeCertificateException: No trust manager was able to validate this certificate chain: # of exceptions = 2
	at play.api.libs.ws.ssl.CompositeX509TrustManager.checkServerTrusted(CompositeX509TrustManager.scala:88)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:999)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
[[31merror[0m] application - 

! @77njpf9p5 - Internal server error, for (POST) [/overview] ->
 
play.api.UnexpectedException: Unexpected exception[ConnectException: General SSLEngine problem]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: java.net.ConnectException: General SSLEngine problem
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:160)
	at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:131)
	at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
Caused by: play.api.libs.ws.ssl.CompositeCertificateException: No trust manager was able to validate this certificate chain: # of exceptions = 2
	at play.api.libs.ws.ssl.CompositeX509TrustManager.checkServerTrusted(CompositeX509TrustManager.scala:88)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:999)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
[[31merror[0m] application - `

I also tried without https:
"http://elasticsearch-elasticsearch-cluster:9200"

But I got the following error:
`play.api.UnexpectedException: Unexpected exception[RemotelyClosedException: Remotely closed]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
[error] application - 
 ! @77nk24n99 - Internal server error, for (POST) [/cluster_changes] -&gt;
 
play.api.UnexpectedException: Unexpected exception[RemotelyClosedException: Remotely closed]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
[error] application - 
 ! @77nk24n9d - Internal server error, for (POST) [/navbar] -&gt;
 
play.api.UnexpectedException: Unexpected exception[RemotelyClosedException: Remotely closed]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
[error] application - 
 ! @77nk24nmc - Internal server error, for (POST) [/overview] -&gt;
`

Have you ever had this? Any idea to provide 😃 ?

Thanks

**Comment by Sneko** [comment]
After accessing Kibana it show me that my ES cluster was unstable:
`
plugin:elasticsearch@6.1.3 | Unable to connect to Elasticsearch at https://elasticsearch-elasticsearch-cluster:9200.
`

I took a look at its logs and saw that:
`[2018-05-03T14:35:17,391][WARN ][o.e.d.z.ZenDiscovery     ] [987d11ba-6aef-4dc9-8ec4-e45ad6966d91] not enough master nodes discovered during pinging (found [[]], but needed [1]), pinging again`

I think it's the origin of the main error above 😀 . But the ES master is healthy and running:
`
[2018-05-03T13:14:57,137][INFO ][o.e.n.Node               ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] initializing ...
[2018-05-03T13:14:57,332][INFO ][o.e.e.NodeEnvironment    ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] using [1] data paths, mounts [[/data (/dev/sdb)]], net usable_space [906.1mb], net total_space [975.8mb], types [ext4]
[2018-05-03T13:14:57,333][INFO ][o.e.e.NodeEnvironment    ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] heap size [247.6mb], compressed ordinary object pointers [true]
[2018-05-03T13:14:57,335][INFO ][o.e.n.Node               ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] node name [79ddb5da-ecf9-438d-9d4a-0e454569e56e], node ID [s1-U73PuSPKmdsgbMQmUjw]
[2018-05-03T13:14:57,335][INFO ][o.e.n.Node               ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] version[6.1.3], pid[1], build[af51318/2018-01-26T18:22:55.523Z], OS[Linux/4.4.64+/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_151/25.151-b12]
[2018-05-03T13:14:57,335][INFO ][o.e.n.Node               ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Xms256m, -Xmx256m, -Des.path.home=/elasticsearch, -Des.path.conf=/elasticsearch/config]
[2018-05-03T13:15:00,193][INFO ][o.e.p.p.PrometheusExporterPlugin] starting Prometheus exporter plugin
[2018-05-03T13:15:00,309][INFO ][c.f.s.s.SearchGuardSSLPlugin] ES Config path is /elasticsearch/config
[2018-05-03T13:15:00,433][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
[2018-05-03T13:15:01,013][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Config directory is /elasticsearch/config/, from there the key- and truststore files are resolved relatively
[2018-05-03T13:15:01,028][INFO ][c.f.s.s.u.SSLCertificateHelper] No alias given, use the first one: elasticsearch-node
[2018-05-03T13:15:01,038][WARN ][c.f.s.s.u.SSLCertificateHelper] Certificate chain for alias elasticsearch-node contains a root certificate
[2018-05-03T13:15:01,138][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] HTTPS client auth mode OPTIONAL
[2018-05-03T13:15:01,142][INFO ][c.f.s.s.u.SSLCertificateHelper] No alias given, use the first one: elasticsearch-node
[2018-05-03T13:15:01,143][WARN ][c.f.s.s.u.SSLCertificateHelper] Certificate chain for alias elasticsearch-node contains a root certificate
[2018-05-03T13:15:01,147][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS Transport Client Provider : JDK
[2018-05-03T13:15:01,152][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS Transport Server Provider : JDK
[2018-05-03T13:15:01,153][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS HTTP Provider             : JDK
[2018-05-03T13:15:01,153][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Enabled TLS protocols for transport layer : [TLSv1.2, TLSv1.1]
[2018-05-03T13:15:01,153][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Enabled TLS protocols for HTTP layer      : [TLSv1.2, TLSv1.1]
[2018-05-03T13:15:01,385][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [aggs-matrix-stats]
[2018-05-03T13:15:01,390][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [analysis-common]
[2018-05-03T13:15:01,390][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [ingest-common]
[2018-05-03T13:15:01,390][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [lang-expression]
[2018-05-03T13:15:01,392][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [lang-mustache]
[2018-05-03T13:15:01,393][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [lang-painless]
[2018-05-03T13:15:01,393][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [mapper-extras]
[2018-05-03T13:15:01,394][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [parent-join]
[2018-05-03T13:15:01,394][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [percolator]
[2018-05-03T13:15:01,394][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [reindex]
[2018-05-03T13:15:01,395][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [repository-url]
[2018-05-03T13:15:01,395][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [transport-netty4]
[2018-05-03T13:15:01,395][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded module [tribe]
[2018-05-03T13:15:01,399][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded plugin [prometheus-exporter]
[2018-05-03T13:15:01,399][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded plugin [repository-s3]
[2018-05-03T13:15:01,400][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded plugin [search-guard-ssl]
[2018-05-03T13:15:01,400][INFO ][o.e.p.PluginsService     ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] loaded plugin [statsd]
[2018-05-03T13:15:05,077][INFO ][o.e.d.DiscoveryModule    ] [79ddb5da-ecf9-438d-9d4a-0e454569e56e] using discovery type [zen]
`

Did I missed something hmmm?
