### ISSUE TITLE
operator crash if other Pods have no component label

### ISSUE THREAD

**Issue by FaKod** [upmc-enterprises/elasticsearch-operator#267]
using Operator 0.2.0 on a GKE cluster 1.11.

If there are other Pods (without component label) in the same namespace as the managed ES Pods, the operator crashes with:

```
panic: runtime error: slice bounds out of range

goroutine 34 [running]:
github.com/upmc-enterprises/elasticsearch-operator/pkg/processor.(*Processor).processPodEvent(0xc4201da480, 0xc4206ff6a0, 0x0, 0x0)
	/Users/stevesloka/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/processor/processor.go:253 +0x268
github.com/upmc-enterprises/elasticsearch-operator/pkg/processor.(*Processor).WatchDataPodEvents.func1(0xc42008a480, 0xc4201da480, 0xc420081440, 0xc42008a960, 0xc4202f2150)
	/Users/stevesloka/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/processor/processor.go:107 +0x1f8
created by github.com/upmc-enterprises/elasticsearch-operator/pkg/processor.(*Processor).WatchDataPodEvents
	/Users/stevesloka/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/processor/processor.go:103 +0x78
```

**Comment by TBBle** [comment]
Probably fixed by #303 in 0.4.0
