### ISSUE TITLE
elasticsearch-operator crashloopbackup 

### ISSUE THREAD

**Issue by bhaskar-chenchu** [upmc-enterprises/elasticsearch-operator#296]
unable to run elasticsearch-operator in AKS 1.12.6 cluster.

error# 
time="2019-04-01T12:25:01Z" level=info msg="elasticsearch operator starting up!"
time="2019-04-01T12:25:01Z" level=info msg="Using Variables:"
time="2019-04-01T12:25:01Z" level=info msg="   enableInitDaemonset: true"
time="2019-04-01T12:25:01Z" level=info msg="   baseImage: upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_0"
time="2019-04-01T12:25:01Z" level=info msg="Using InCluster k8s config"
time="2019-04-01T12:25:01Z" level=info msg="SKIPPING: already exists \"elasticsearchclusters.enterprises.upmc.com\""
time="2019-04-01T12:25:01Z" level=info msg="Daemonset default/elasticsearch-operator-sysctl already exist, skipping creation ..."
time="2019-04-01T12:25:01Z" level=info msg="Found 0 existing clusters "
time="2019-04-01T12:25:01Z" level=info msg="Watching for elasticsearch events..."
panic: runtime error: slice bounds out of range
 goroutine 29 [running]:
github.com/upmc-enterprises/elasticsearch-operator/pkg/processor.(*Processor).processDataPodEvent(0xc0002dedc0, 0xc0001e89a8, 0x10b0148, 0x4)
	/home/steve/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/processor/processor.go:285 +0x205
github.com/upmc-enterprises/elasticsearch-operator/pkg/processor.(*Processor).processPodEvent(0xc0002dedc0, 0xc0001e89a8, 0x0, 0x0)
	/home/steve/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/processor/processor.go:275 +0x137
github.com/upmc-enterprises/elasticsearch-operator/pkg/processor.(*Processor).WatchDataPodEvents.func1(0xc00032e060, 0xc0002dedc0, 0xc0002a1bc0, 0xc0000a8b40, 0xc0002babc0)
	/home/steve/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/processor/processor.go:109 +0x1ed
created by github.com/upmc-enterprises/elasticsearch-operator/pkg/processor.(*Processor).WatchDataPodEvents
	/home/steve/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/processor/processor.go:105 +0x78

--------------------------

AKS version# 1.12.6
es-oss ver# 6.4.2
kibana-oss ver#6.4.3 (with log trail)

**Comment by stevesloka** [comment]
@bhaskar-chenchu do you have any cluster CRD's defined?

**Comment by bhaskar-chenchu** [comment]
> @bhaskar-chenchu do you have any cluster CRD's defined?

@stevesloka ,  as part of ES-Operator, no.  As part of Istio installation, yes.  standard Istio defined CRDS of Istio-deployment. (https://istio.io/docs/setup/kubernetes/install/kubernetes/).

**Comment by stevesloka** [comment]
What I meant are did you apply any elasticsearchcluster crd's? e.g. kubectl get elasticsearchclusters

**Comment by TBBle** [comment]
Probably fixed by #303 in 0.4.0
