### ISSUE TITLE
Problems with Elasticsearch statd-plugin during startup of controller.yaml

### ISSUE THREAD

**Issue by snsumner** [upmc-enterprises/elasticsearch-operator#34]
I successfully had your elasticsearch-operator working with Tectonic 1.6.2 release candidate.  I rebuilt my cluster to Tectonic 1.6.2.tectonic.1 (GA) and now when I tried to deploy controller.yaml both the es-master and es-client pods are failing with the following error

```
[2017-05-12T16:33:55,627][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [a68dcdc1-c226-4dd3-ac80-592e6a3123df] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:
1) Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService
1 error
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
Caused by: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:
1) Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService
1 error
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:771) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:801) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
	at org.elasticsearch.node.Node.<init>(Node.java:495) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
Caused by: com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:115) ~[?:?]
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:82) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:75) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:72) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at com.automattic.elasticsearch.statsd.StatsdService.<init>(StatsdService.java:72) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4$1.call(InjectorImpl.java:762) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:757) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:801) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
	at org.elasticsearch.node.Node.<init>(Node.java:495) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
Caused by: java.net.SocketException: Unresolved address
	at java.net.DatagramSocket.connect(DatagramSocket.java:493) ~[?:1.8.0_121]
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:113) ~[?:?]
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:82) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:75) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:72) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at com.automattic.elasticsearch.statsd.StatsdService.<init>(StatsdService.java:72) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4$1.call(InjectorImpl.java:762) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:757) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:801) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
	at org.elasticsearch.node.Node.<init>(Node.java:495) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
```
I've tried 0.0.2 and 0.0.3-beta and get the same results.  Any suggestion on what could be causing this error?

**Comment by stevesloka** [comment]
Hey @snsumner, sorry for the trouble. The problem is I added a statsd plugin to the base elasticsearch image so you can push metrics to statsd. 

The problem is if you don't have a statsd endpoint listening, it blows up. 

You can change the base image the cluster will use by adding it to the TPR before you create the cluster. Add a field named: `elastic-search-image` and override the base elastic image. If you want ES 5.3.1 use this image: `upmcenterprises/docker-elasticsearch-kubernetes:5.3.1` 

That image does not have the statsd plugin installed by default.

**Comment by snsumner** [comment]
Hey @stevesloka thanks for the workaround it did solve my problem.  I'm successfully running your Elasticsearch operator + Kibana 5.3.2 on Tectonic 1.6.2.tectonic.1 and have configured aggregation of tectonic logs to elasticsearch using Chance's logging [instructions](https://github.com/coreos/tectonic-installer/blob/master/Documentation/admin/logging.md).  I now plan to create a helm chart to deploy everything together.

**Comment by stevesloka** [comment]
Awesome glad to hear! Please let me know if you have any further issues or comments on how to make it better. Would appreciate the feedback!

**Comment by splisson-altair** [comment]
@snsumner I'm also working on an helm chart. Are you combining operator installation and cluster deployment as they did for etcd-operator ? Also I'm not sure if the template in yaml is transformed to json by helm (elsaticsearch operator seems to take only json as input. I red yaml is a superset of json but when I tried yam I got some errors in the operator

**Comment by splisson-altair** [comment]
@stevesloka @snsumner 
Where did you add the elastic-search-image field in the TPR ?
I get a validation error when I try to save the change

**Comment by snsumner** [comment]
@splisson-altair yes I'm trying to combine operator installation and cluster deployment.  I'm not familiar with how they did it for etcd-operator.   When I try to do a helm install I get the following error messages: 

```[Mon May 22 21:20:50 core@jumpbox:~/github/snsumner ] $ helm install --debug --dry-run elasticsearch-operator-helm/
[debug] Created tunnel using local port: '34044'

[debug] SERVER: "localhost:34044"

[debug] CHART PATH: /home/core/github/snsumner/elasticsearch-operator-helm

Error: apiVersion "enterprises.upmc.com/v1" in elasticsearch-operator-helm/templates/elasticsearchcluster.yaml is not available
[Mon May 22 21:20:56 core@jumpbox:~/github/snsumner ] $
```
I converted all the json documents to yaml and it appears there is a problem.  I have not figured out a workaround yet.

**Comment by snsumner** [comment]
I'm a recent hire at CoreOS on the solutions engineering team.  And one of my first tasks was creating a demo to show how to aggregated logs in Tectonic using Fluentd, store them in Elasticsearch, and access them from Kibana web UI.  I leveraged the work of Steve and others to create a cool demo which uses helm to deploy all three components within Kubernetes.  You can access my work here:

https://quay.io/application/snsumner75/elasticsearch-operator-helm
https://quay.io/application/snsumner75/kibana-helm
https://quay.io/application/chancez-apps/fluentd

I'm using Chance's helm for deploying fluentd to aggregate logs in Tectonic.

You need all three of these tools to do the deployment:

- [Kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl)

- [Helm](https://github.com/kubernetes/helm/blob/master/docs/install.md)

- [Helm

 Registry Plugin](https://coreos.com/blog/quay-application-registry-for-kubernetes.html)

`$ helm registry install quay.io/snsumner75/elasticsearch-operator-helm`
`$ helm registry upgrade http://quay.io/snsumner75/elasticsearch-operator-helm hardy-deer`

Optional:
`$ helm registry upgrade http://quay.io/snsumner75/elasticsearch-operator-helm hardy-deer --set es_master_replicas=2 --set es_client_replicas=3 --set es_data_replicas=3`

`$ helm registry install quay.io/snsumner75/kibana-helm`

`$ helm registry install quay.io/chancez-apps/fluentd --namespace logging --set 'output.elasticsearch.scheme=https'`

If you have questions you can ping me at scott@coreos.com.  Love to get feedback this is my first experience with Kubernetes and I'm still a greenie.
