### ISSUE TITLE
StatsD Exception at Launch

### ISSUE THREAD

**Issue by splisson-altair** [upmc-enterprises/elasticsearch-operator#41]
I'm getting the following exception in the logs of es-client pod  when the cluster is launching:

[2017-05-19T00:40:52,024][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [3d88392d-7a72-4e10-b67f-ba060f43ca56] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

1 error
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
Caused by: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

1 error
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:771) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:801) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
	at org.elasticsearch.node.Node.<init>(Node.java:495) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
Caused by: com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:115) ~[?:?]
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:82) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:75) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:72) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at com.automattic.elasticsearch.statsd.StatsdService.<init>(StatsdService.java:72) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4$1.call(InjectorImpl.java:762) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:757) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:801) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
	at org.elasticsearch.node.Node.<init>(Node.java:495) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
Caused by: java.net.SocketException: Unresolved address
	at java.net.DatagramSocket.connect(DatagramSocket.java:493) ~[?:1.8.0_121]
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:113) ~[?:?]
	at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:82) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:75) ~[?:?]
	at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:72) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at com.automattic.elasticsearch.statsd.StatsdService.<init>(StatsdService.java:72) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4$1.call(InjectorImpl.java:762) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:757) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:801) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
	at org.elasticsearch.node.Node.<init>(Node.java:495) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]

my cluster.json:
```

{
  "apiVersion": "enterprises.upmc.com/v1",
  "kind": "ElasticsearchCluster",
  "metadata": {
    "chart": "search-test-api-dev",
    "app": "search-test-api-dev",
    "heritage": "helm",
    "release": "search-test-api-dev",
    "name": "es-cluster-test-api-dev"
  },
  "spec": {
    "client-node-replicas": 2,
    "master-node-replicas": 2,
    "data-node-replicas": 2,
    "zones": ["us-east-1a", "us-east-1b"],
    "data-volume-size": "10Gi",
    "java-options": "-Xms256m -Xmx256m",
    "snapshot": {
      "scheduler-enabled": false,
      "bucket-name": "elasticsnapshots99",
      "cron-schedule": "@every 2m"
    },
    "storage": {
      "type": "gp2",
      "storage-class-provisioner": "kubernetes.io/aws-ebs"
    },
    "resources": {
      "requests": {
         "memory": "256Mi",
         "cpu": "200m"
      },
      "limits": {
        "memory": "1024Mi",
        "cpu": "1"
      }
    }
  }
}
```

Any idea ?

I saw a post with an option to turn off statsd but that would require modifying the elasticsearch config

**Comment by splisson-altair** [comment]
duplicate

**Comment by stevesloka** [comment]
Yeah sorry about that @splisson-altair, I'm working on a way to make this better. There's a way you can install plugins via ENV variable, but I don't like that for production use-cases. I'll update the default example at least to no use the statsd container.

**Comment by splisson-altair** [comment]
no worry, I appreciate your work on this operator!
