### ISSUE TITLE
Failing to start statsd

### ISSUE THREAD

**Issue by dvdklnr** [upmc-enterprises/elasticsearch-operator#46]
```[2017-05-24T01:29:47,909][INFO ][o.e.p.PluginsService     ] [d50ae762-605a-4651-9411-373e0a3f8e8f] loaded plugin [statsd]
[2017-05-24T01:29:48,225][WARN ][d.m.attachment           ] [mapper-attachments] plugin has been deprecated and will be replaced by [ingest-attachment] plugin.
[2017-05-24T01:29:53,096][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [d50ae762-605a-4651-9411-373e0a3f8e8f] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

1 error
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
Caused by: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService
```

<...>
```
Caused by: java.net.SocketException: Unresolved address
        at java.net.DatagramSocket.connect(DatagramSocket.java:493) ~[?:1.8.0_121]
        at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:113) ~[?:?]
```

**Comment by dvdklnr** [comment]
cluster version detail:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by stevesloka** [comment]
The latest version of the base image uses statsd to write metrics, if that's not there then ES breaks. The best bet is to swap out your base image referenced here: https://github.com/upmc-enterprises/elasticsearch-operator/issues/34#issuecomment-301139372

I'm working to make the docs better to explain this as well as make it fail less hard so the cluster can still function.

**Comment by dvdklnr** [comment]
Thank you Steve
